[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 5000

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4b7bec"
backgroundColor = "#20252e"
secondaryBackgroundColor = "#2d3436"
textColor = "#f0f0f0"
font = "sans-serif"

# This setting allows us to optimize the sidebar and hide entries
[ui]
hideSidebarNav = true